
version: '3'
services:
  db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - /storage/nextcloud-db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped

  app:
    build: ./app
    container_name: nextcloud-app
    restart: unless-stopped
    volumes:
      - ./app/www2.conf:/usr/local/etc/php-fpm.d/www2.conf:ro
      - ./app/nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - /storage/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: nextcloud-web
    restart: unless-stopped
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - /storage/nextcloud:/var/www/html:ro
    depends_on:
      - app

networks:
  default:
    external:
      name: proxy-net
